import FeatureBox from "./FeatureBox";

const feature = [
  {
    title: "AI Contract Generation",
    description:
      "Input prompts and details, and watch as LegalGenius dynamically generates comprehensive contracts and agreements, streamlining the drafting process and ensuring accuracy.",
    benefit:
      "Save hours of manual work, increase efficiency, and minimize errors in contract creation.",
  },
  {
    title: "Document Understanding",
    description:
      "Easily upload legal documents to LegalGenius and receive clear, concise explanations generated by our AI algorithms. Understanding complex legal jargon has never been easier.",
    benefit:
      "Empower individuals to comprehend legal documents without the need for a lawyer, fostering accessibility and transparency in legal matters.",
  },
  {
    title: "Case Comparison and Insights",
    description:
      "Upload current case documents to LegalGenius for instant comparison with past cases, providing valuable insights and references to inform legal strategies.",
    benefit:
      "Enhance case preparation, make informed decisions, and leverage past precedents to strengthen arguments.",
  },
];
const FeatureSection = () => {
  return (
    <div>
      <div>Our Platform Feature</div>
      <div className="flex flex-row md:flex-col flex-wrap">
        <div>
          {feature.map((e, index) => {
            return (
              <FeatureBox
                title={e.title}
                description={e.description}
                benefit={e.benefit}
                key={index}
              />
            );
          })}
        </div>
      </div>
    </div>
  );
};
export default FeatureSection;
